// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: entrypoint.proto

package mbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 运行状态
type RunStatus int32

const (
	RunStatus_Unknown    RunStatus = 0  // 未知
	RunStatus_NotRunning RunStatus = 2  // 未运行
	RunStatus_Scheme     RunStatus = 4  // 计划中
	RunStatus_Running    RunStatus = 8  // 运行中
	RunStatus_Success    RunStatus = 16 // 运行成功
	RunStatus_Fail       RunStatus = 32 // 运行失败
	RunStatus_Cancel     RunStatus = 64 // 已取消
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0:  "Unknown",
		2:  "NotRunning",
		4:  "Scheme",
		8:  "Running",
		16: "Success",
		32: "Fail",
		64: "Cancel",
	}
	RunStatus_value = map[string]int32{
		"Unknown":    0,
		"NotRunning": 2,
		"Scheme":     4,
		"Running":    8,
		"Success":    16,
		"Fail":       32,
		"Cancel":     64,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_entrypoint_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_entrypoint_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunStatus.Descriptor instead.
func (RunStatus) EnumDescriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{0}
}

// 间隔时间执行类型
type EveryType int32

const (
	EveryType_EvNone   EveryType = 0 // 未定义
	EveryType_EvMinute EveryType = 1 // 分钟
	EveryType_EvHour   EveryType = 2 // 小时
	EveryType_EvDay    EveryType = 3 // 天
	EveryType_EvWeek   EveryType = 4 // 周
	EveryType_EvMonth  EveryType = 5 // 月
)

// Enum value maps for EveryType.
var (
	EveryType_name = map[int32]string{
		0: "EvNone",
		1: "EvMinute",
		2: "EvHour",
		3: "EvDay",
		4: "EvWeek",
		5: "EvMonth",
	}
	EveryType_value = map[string]int32{
		"EvNone":   0,
		"EvMinute": 1,
		"EvHour":   2,
		"EvDay":    3,
		"EvWeek":   4,
		"EvMonth":  5,
	}
)

func (x EveryType) Enum() *EveryType {
	p := new(EveryType)
	*p = x
	return p
}

func (x EveryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EveryType) Descriptor() protoreflect.EnumDescriptor {
	return file_entrypoint_proto_enumTypes[1].Descriptor()
}

func (EveryType) Type() protoreflect.EnumType {
	return &file_entrypoint_proto_enumTypes[1]
}

func (x EveryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EveryType.Descriptor instead.
func (EveryType) EnumDescriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{1}
}

// 周期类型
type EveryTimeType int32

const (
	EveryTimeType_EveryNone    EveryTimeType = 0 // 未知
	EveryTimeType_EveryDay     EveryTimeType = 1 // 每天
	EveryTimeType_EveryWeek    EveryTimeType = 2 // 每周
	EveryTimeType_EveryMonth   EveryTimeType = 3 // 每月
	EveryTimeType_EveryQuarter EveryTimeType = 4 // 每季
	EveryTimeType_EveryYear    EveryTimeType = 5 // 每年
)

// Enum value maps for EveryTimeType.
var (
	EveryTimeType_name = map[int32]string{
		0: "EveryNone",
		1: "EveryDay",
		2: "EveryWeek",
		3: "EveryMonth",
		4: "EveryQuarter",
		5: "EveryYear",
	}
	EveryTimeType_value = map[string]int32{
		"EveryNone":    0,
		"EveryDay":     1,
		"EveryWeek":    2,
		"EveryMonth":   3,
		"EveryQuarter": 4,
		"EveryYear":    5,
	}
)

func (x EveryTimeType) Enum() *EveryTimeType {
	p := new(EveryTimeType)
	*p = x
	return p
}

func (x EveryTimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EveryTimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_entrypoint_proto_enumTypes[2].Descriptor()
}

func (EveryTimeType) Type() protoreflect.EnumType {
	return &file_entrypoint_proto_enumTypes[2]
}

func (x EveryTimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EveryTimeType.Descriptor instead.
func (EveryTimeType) EnumDescriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{2}
}

// 启用请求
type EnableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DBInfo       *DBDetail `protobuf:"bytes,1,opt,name=DBInfo,proto3" json:"DBInfo,omitempty"`             // 数据库信息
	EnterpriseID string    `protobuf:"bytes,2,opt,name=EnterpriseID,proto3" json:"EnterpriseID,omitempty"` // 企业ID
	CardId       int64     `protobuf:"varint,3,opt,name=CardId,proto3" json:"CardId,omitempty"`            // Card ID
	Crontab      *Crontab  `protobuf:"bytes,4,opt,name=Crontab,proto3,oneof" json:"Crontab,omitempty"`     //运行周期表达式
	SqlScript    string    `protobuf:"bytes,5,opt,name=SqlScript,proto3" json:"SqlScript,omitempty"`       // SQL代码
	Tables       *Tables   `protobuf:"bytes,6,opt,name=Tables,proto3" json:"Tables,omitempty"`             // SQL引用的实体表
	Extra        *Extra    `protobuf:"bytes,7,opt,name=Extra,proto3,oneof" json:"Extra,omitempty"`         // 附加信息
}

func (x *EnableRequest) Reset() {
	*x = EnableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableRequest) ProtoMessage() {}

func (x *EnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableRequest.ProtoReflect.Descriptor instead.
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{0}
}

func (x *EnableRequest) GetDBInfo() *DBDetail {
	if x != nil {
		return x.DBInfo
	}
	return nil
}

func (x *EnableRequest) GetEnterpriseID() string {
	if x != nil {
		return x.EnterpriseID
	}
	return ""
}

func (x *EnableRequest) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *EnableRequest) GetCrontab() *Crontab {
	if x != nil {
		return x.Crontab
	}
	return nil
}

func (x *EnableRequest) GetSqlScript() string {
	if x != nil {
		return x.SqlScript
	}
	return ""
}

func (x *EnableRequest) GetTables() *Tables {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *EnableRequest) GetExtra() *Extra {
	if x != nil {
		return x.Extra
	}
	return nil
}

// 实体表切片
type Tables struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table []*Table `protobuf:"bytes,1,rep,name=Table,proto3" json:"Table,omitempty"`
}

func (x *Tables) Reset() {
	*x = Tables{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tables) ProtoMessage() {}

func (x *Tables) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tables.ProtoReflect.Descriptor instead.
func (*Tables) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{1}
}

func (x *Tables) GetTable() []*Table {
	if x != nil {
		return x.Table
	}
	return nil
}

// 字段切片
type Columns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column []*Column `protobuf:"bytes,1,rep,name=Column,proto3" json:"Column,omitempty"` // 字段
}

func (x *Columns) Reset() {
	*x = Columns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Columns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Columns) ProtoMessage() {}

func (x *Columns) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Columns.ProtoReflect.Descriptor instead.
func (*Columns) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{2}
}

func (x *Columns) GetColumn() []*Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// 启用回复
type EnableReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutTable    *Table                 `protobuf:"bytes,1,opt,name=OutTable,proto3" json:"OutTable,omitempty"`             // 结果表
	Columns     *Columns               `protobuf:"bytes,2,opt,name=Columns,proto3" json:"Columns,omitempty"`               // 字段类
	NextRunTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=NextRunTime,proto3,oneof" json:"NextRunTime,omitempty"` // 下次运行时间
	Error       *Error                 `protobuf:"bytes,4,opt,name=Error,proto3,oneof" json:"Error,omitempty"`             // 错误信息 可选
}

func (x *EnableReply) Reset() {
	*x = EnableReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableReply) ProtoMessage() {}

func (x *EnableReply) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableReply.ProtoReflect.Descriptor instead.
func (*EnableReply) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{3}
}

func (x *EnableReply) GetOutTable() *Table {
	if x != nil {
		return x.OutTable
	}
	return nil
}

func (x *EnableReply) GetColumns() *Columns {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *EnableReply) GetNextRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunTime
	}
	return nil
}

func (x *EnableReply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 行动请求
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnterpriseID string `protobuf:"bytes,1,opt,name=EnterpriseID,proto3" json:"EnterpriseID,omitempty"` // 企业ID
	CardId       int64  `protobuf:"varint,2,opt,name=CardId,proto3" json:"CardId,omitempty"`            // Card ID
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetEnterpriseID() string {
	if x != nil {
		return x.EnterpriseID
	}
	return ""
}

func (x *Request) GetCardId() int64 {
	if x != nil {
		return x.CardId
	}
	return 0
}

// 行动回复
type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        *string  `protobuf:"bytes,1,opt,name=Key,proto3,oneof" json:"Key,omitempty"`                // Key
	SequenceID *int64   `protobuf:"varint,2,opt,name=SequenceID,proto3,oneof" json:"SequenceID,omitempty"` // 序列ID
	Columns    *Columns `protobuf:"bytes,3,opt,name=Columns,proto3,oneof" json:"Columns,omitempty"`        // 字段类
	Error      *Error   `protobuf:"bytes,4,opt,name=Error,proto3,oneof" json:"Error,omitempty"`            // 错误信息 可选
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{5}
}

func (x *Reply) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *Reply) GetSequenceID() int64 {
	if x != nil && x.SequenceID != nil {
		return *x.SequenceID
	}
	return 0
}

func (x *Reply) GetColumns() *Columns {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Reply) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// 实体表
type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema string `protobuf:"bytes,1,opt,name=Schema,proto3" json:"Schema,omitempty"`
	Table  string `protobuf:"bytes,2,opt,name=Table,proto3" json:"Table,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{6}
}

func (x *Table) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *Table) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

// 字段类
type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{7}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 数据库信息
type DBDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DBType        string            `protobuf:"bytes,1,opt,name=DBType,proto3" json:"DBType,omitempty"`                                                                                                       //数据库类型
	Host          string            `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`                                                                                                           //数据主机地址
	Port          int32             `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`                                                                                                          //数据库端口
	User          string            `protobuf:"bytes,4,opt,name=User,proto3" json:"User,omitempty"`                                                                                                           //数据库用户名
	Pwd           string            `protobuf:"bytes,5,opt,name=Pwd,proto3" json:"Pwd,omitempty"`                                                                                                             //数据库密码
	DBName        string            `protobuf:"bytes,6,opt,name=DBName,proto3" json:"DBName,omitempty"`                                                                                                       //数据库名称
	ConnectParams map[string]string `protobuf:"bytes,7,rep,name=ConnectParams,proto3" json:"ConnectParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 连接参数
}

func (x *DBDetail) Reset() {
	*x = DBDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBDetail) ProtoMessage() {}

func (x *DBDetail) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBDetail.ProtoReflect.Descriptor instead.
func (*DBDetail) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{8}
}

func (x *DBDetail) GetDBType() string {
	if x != nil {
		return x.DBType
	}
	return ""
}

func (x *DBDetail) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DBDetail) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DBDetail) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DBDetail) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *DBDetail) GetDBName() string {
	if x != nil {
		return x.DBName
	}
	return ""
}

func (x *DBDetail) GetConnectParams() map[string]string {
	if x != nil {
		return x.ConnectParams
	}
	return nil
}

// 执行一次
type CycleOnce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression *Expression `protobuf:"bytes,1,opt,name=Expression,proto3" json:"Expression,omitempty"` // 表达式
}

func (x *CycleOnce) Reset() {
	*x = CycleOnce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleOnce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleOnce) ProtoMessage() {}

func (x *CycleOnce) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleOnce.ProtoReflect.Descriptor instead.
func (*CycleOnce) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{9}
}

func (x *CycleOnce) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

// 间隔时间执行
type CycleEvery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EveryExpress *EveryExpress `protobuf:"bytes,1,opt,name=EveryExpress,proto3" json:"EveryExpress,omitempty"`   // 间隔周期
	Expression   *Expression   `protobuf:"bytes,2,opt,name=Expression,proto3,oneof" json:"Expression,omitempty"` // 表达式
}

func (x *CycleEvery) Reset() {
	*x = CycleEvery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleEvery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleEvery) ProtoMessage() {}

func (x *CycleEvery) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleEvery.ProtoReflect.Descriptor instead.
func (*CycleEvery) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{10}
}

func (x *CycleEvery) GetEveryExpress() *EveryExpress {
	if x != nil {
		return x.EveryExpress
	}
	return nil
}

func (x *CycleEvery) GetExpression() *Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

// 间隔周期
type EveryExpress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CycleType  EveryType `protobuf:"varint,1,opt,name=CycleType,proto3,enum=mbpb.EveryType" json:"CycleType,omitempty"` // 类型
	CycleValue int32     `protobuf:"varint,2,opt,name=CycleValue,proto3" json:"CycleValue,omitempty"`                   // Value
}

func (x *EveryExpress) Reset() {
	*x = EveryExpress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EveryExpress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EveryExpress) ProtoMessage() {}

func (x *EveryExpress) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EveryExpress.ProtoReflect.Descriptor instead.
func (*EveryExpress) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{11}
}

func (x *EveryExpress) GetCycleType() EveryType {
	if x != nil {
		return x.CycleType
	}
	return EveryType_EvNone
}

func (x *EveryExpress) GetCycleValue() int32 {
	if x != nil {
		return x.CycleValue
	}
	return 0
}

// 表达式
type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Express string `protobuf:"bytes,1,opt,name=Express,proto3" json:"Express,omitempty"` // 表达式
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{12}
}

func (x *Expression) GetExpress() string {
	if x != nil {
		return x.Express
	}
	return ""
}

// 时间循环周期执行
type CycleEveryTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EveryType EveryTimeType `protobuf:"varint,1,opt,name=EveryType,proto3,enum=mbpb.EveryTimeType" json:"EveryType,omitempty"` // 类型
	// Types that are assignable to EveryTime:
	//
	//	*CycleEveryTime_EveryDay
	//	*CycleEveryTime_EveryWeek
	//	*CycleEveryTime_EveryMonth
	//	*CycleEveryTime_EveryQuarter
	//	*CycleEveryTime_EveryYear
	EveryTime isCycleEveryTime_EveryTime `protobuf_oneof:"EveryTime"`
}

func (x *CycleEveryTime) Reset() {
	*x = CycleEveryTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleEveryTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleEveryTime) ProtoMessage() {}

func (x *CycleEveryTime) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleEveryTime.ProtoReflect.Descriptor instead.
func (*CycleEveryTime) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{13}
}

func (x *CycleEveryTime) GetEveryType() EveryTimeType {
	if x != nil {
		return x.EveryType
	}
	return EveryTimeType_EveryNone
}

func (m *CycleEveryTime) GetEveryTime() isCycleEveryTime_EveryTime {
	if m != nil {
		return m.EveryTime
	}
	return nil
}

func (x *CycleEveryTime) GetEveryDay() *CycleEveryDay {
	if x, ok := x.GetEveryTime().(*CycleEveryTime_EveryDay); ok {
		return x.EveryDay
	}
	return nil
}

func (x *CycleEveryTime) GetEveryWeek() *CycleEveryWeekMonth {
	if x, ok := x.GetEveryTime().(*CycleEveryTime_EveryWeek); ok {
		return x.EveryWeek
	}
	return nil
}

func (x *CycleEveryTime) GetEveryMonth() *CycleEveryWeekMonth {
	if x, ok := x.GetEveryTime().(*CycleEveryTime_EveryMonth); ok {
		return x.EveryMonth
	}
	return nil
}

func (x *CycleEveryTime) GetEveryQuarter() *CycleEveryYear {
	if x, ok := x.GetEveryTime().(*CycleEveryTime_EveryQuarter); ok {
		return x.EveryQuarter
	}
	return nil
}

func (x *CycleEveryTime) GetEveryYear() *CycleEveryYear {
	if x, ok := x.GetEveryTime().(*CycleEveryTime_EveryYear); ok {
		return x.EveryYear
	}
	return nil
}

type isCycleEveryTime_EveryTime interface {
	isCycleEveryTime_EveryTime()
}

type CycleEveryTime_EveryDay struct {
	EveryDay *CycleEveryDay `protobuf:"bytes,3,opt,name=EveryDay,proto3,oneof"` // 每天
}

type CycleEveryTime_EveryWeek struct {
	EveryWeek *CycleEveryWeekMonth `protobuf:"bytes,4,opt,name=EveryWeek,proto3,oneof"` // 每周
}

type CycleEveryTime_EveryMonth struct {
	EveryMonth *CycleEveryWeekMonth `protobuf:"bytes,5,opt,name=EveryMonth,proto3,oneof"` // 每月
}

type CycleEveryTime_EveryQuarter struct {
	EveryQuarter *CycleEveryYear `protobuf:"bytes,6,opt,name=EveryQuarter,proto3,oneof"` // 每季
}

type CycleEveryTime_EveryYear struct {
	EveryYear *CycleEveryYear `protobuf:"bytes,7,opt,name=EveryYear,proto3,oneof"` // 每年
}

func (*CycleEveryTime_EveryDay) isCycleEveryTime_EveryTime() {}

func (*CycleEveryTime_EveryWeek) isCycleEveryTime_EveryTime() {}

func (*CycleEveryTime_EveryMonth) isCycleEveryTime_EveryTime() {}

func (*CycleEveryTime_EveryQuarter) isCycleEveryTime_EveryTime() {}

func (*CycleEveryTime_EveryYear) isCycleEveryTime_EveryTime() {}

// 每天
type CycleEveryDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunTime *CycleHour `protobuf:"bytes,1,opt,name=RunTime,proto3" json:"RunTime,omitempty"` // 运行时间
}

func (x *CycleEveryDay) Reset() {
	*x = CycleEveryDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleEveryDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleEveryDay) ProtoMessage() {}

func (x *CycleEveryDay) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleEveryDay.ProtoReflect.Descriptor instead.
func (*CycleEveryDay) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{14}
}

func (x *CycleEveryDay) GetRunTime() *CycleHour {
	if x != nil {
		return x.RunTime
	}
	return nil
}

// 每月
type CycleEveryWeekMonth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunTime *CycleHour `protobuf:"bytes,1,opt,name=RunTime,proto3" json:"RunTime,omitempty"` // 运行时间
	Day     *CycleDay  `protobuf:"bytes,2,opt,name=Day,proto3" json:"Day,omitempty"`         // 天
}

func (x *CycleEveryWeekMonth) Reset() {
	*x = CycleEveryWeekMonth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleEveryWeekMonth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleEveryWeekMonth) ProtoMessage() {}

func (x *CycleEveryWeekMonth) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleEveryWeekMonth.ProtoReflect.Descriptor instead.
func (*CycleEveryWeekMonth) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{15}
}

func (x *CycleEveryWeekMonth) GetRunTime() *CycleHour {
	if x != nil {
		return x.RunTime
	}
	return nil
}

func (x *CycleEveryWeekMonth) GetDay() *CycleDay {
	if x != nil {
		return x.Day
	}
	return nil
}

// 执行周期按年
type CycleEveryYear struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunTime *CycleHour          `protobuf:"bytes,1,opt,name=RunTime,proto3" json:"RunTime,omitempty"`                                                                                  // 运行时间
	Day     map[int32]*CycleDay `protobuf:"bytes,2,rep,name=Day,proto3" json:"Day,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 天 切片 -1=最后1天
}

func (x *CycleEveryYear) Reset() {
	*x = CycleEveryYear{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleEveryYear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleEveryYear) ProtoMessage() {}

func (x *CycleEveryYear) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleEveryYear.ProtoReflect.Descriptor instead.
func (*CycleEveryYear) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{16}
}

func (x *CycleEveryYear) GetRunTime() *CycleHour {
	if x != nil {
		return x.RunTime
	}
	return nil
}

func (x *CycleEveryYear) GetDay() map[int32]*CycleDay {
	if x != nil {
		return x.Day
	}
	return nil
}

// 小时
type CycleHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hour   []int32 `protobuf:"varint,1,rep,packed,name=Hour,proto3" json:"Hour,omitempty"`     // 小时 切片
	Minute []int32 `protobuf:"varint,2,rep,packed,name=Minute,proto3" json:"Minute,omitempty"` // 分钟 切片
}

func (x *CycleHour) Reset() {
	*x = CycleHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleHour) ProtoMessage() {}

func (x *CycleHour) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleHour.ProtoReflect.Descriptor instead.
func (*CycleHour) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{17}
}

func (x *CycleHour) GetHour() []int32 {
	if x != nil {
		return x.Hour
	}
	return nil
}

func (x *CycleHour) GetMinute() []int32 {
	if x != nil {
		return x.Minute
	}
	return nil
}

// 每月
type CycleDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 某天 -1 为最后1天
	Day []int32 `protobuf:"varint,1,rep,packed,name=Day,proto3" json:"Day,omitempty"` // 天 切片
}

func (x *CycleDay) Reset() {
	*x = CycleDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CycleDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CycleDay) ProtoMessage() {}

func (x *CycleDay) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CycleDay.ProtoReflect.Descriptor instead.
func (*CycleDay) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{18}
}

func (x *CycleDay) GetDay() []int32 {
	if x != nil {
		return x.Day
	}
	return nil
}

type CommonConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zone      string  `protobuf:"bytes,1,opt,name=Zone,proto3" json:"Zone,omitempty"`             // 时区
	StartTime string  `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`   // 执行时间
	EndTime   *string `protobuf:"bytes,3,opt,name=EndTime,proto3,oneof" json:"EndTime,omitempty"` // 结束时间 无限期为null
}

func (x *CommonConfig) Reset() {
	*x = CommonConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonConfig) ProtoMessage() {}

func (x *CommonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonConfig.ProtoReflect.Descriptor instead.
func (*CommonConfig) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{19}
}

func (x *CommonConfig) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *CommonConfig) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CommonConfig) GetEndTime() string {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return ""
}

// Crontab表达式
type Crontab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 调度状态
	Enable       bool          `protobuf:"varint,1,opt,name=Enable,proto3" json:"Enable,omitempty"`
	CommonConfig *CommonConfig `protobuf:"bytes,2,opt,name=CommonConfig,proto3" json:"CommonConfig,omitempty"` // 公共配置
	// 执行周期
	//
	// Types that are assignable to Cycle:
	//
	//	*Crontab_CycleOnce
	//	*Crontab_CycleEvery
	//	*Crontab_CycleEveryTime
	Cycle isCrontab_Cycle `protobuf_oneof:"Cycle"`
}

func (x *Crontab) Reset() {
	*x = Crontab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crontab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crontab) ProtoMessage() {}

func (x *Crontab) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crontab.ProtoReflect.Descriptor instead.
func (*Crontab) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{20}
}

func (x *Crontab) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Crontab) GetCommonConfig() *CommonConfig {
	if x != nil {
		return x.CommonConfig
	}
	return nil
}

func (m *Crontab) GetCycle() isCrontab_Cycle {
	if m != nil {
		return m.Cycle
	}
	return nil
}

func (x *Crontab) GetCycleOnce() *CycleOnce {
	if x, ok := x.GetCycle().(*Crontab_CycleOnce); ok {
		return x.CycleOnce
	}
	return nil
}

func (x *Crontab) GetCycleEvery() *CycleEvery {
	if x, ok := x.GetCycle().(*Crontab_CycleEvery); ok {
		return x.CycleEvery
	}
	return nil
}

func (x *Crontab) GetCycleEveryTime() *CycleEveryTime {
	if x, ok := x.GetCycle().(*Crontab_CycleEveryTime); ok {
		return x.CycleEveryTime
	}
	return nil
}

type isCrontab_Cycle interface {
	isCrontab_Cycle()
}

type Crontab_CycleOnce struct {
	CycleOnce *CycleOnce `protobuf:"bytes,3,opt,name=CycleOnce,proto3,oneof"` // 执行1次
}

type Crontab_CycleEvery struct {
	CycleEvery *CycleEvery `protobuf:"bytes,4,opt,name=CycleEvery,proto3,oneof"` // 周期间隔
}

type Crontab_CycleEveryTime struct {
	CycleEveryTime *CycleEveryTime `protobuf:"bytes,5,opt,name=CycleEveryTime,proto3,oneof"` // 时间循环周期执行
}

func (*Crontab_CycleOnce) isCrontab_Cycle() {}

func (*Crontab_CycleEvery) isCrontab_Cycle() {}

func (*Crontab_CycleEveryTime) isCrontab_Cycle() {}

// Fully Qualified Name
type FQN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Schema string `protobuf:"bytes,1,opt,name=Schema,proto3" json:"Schema,omitempty"`
	Table  string `protobuf:"bytes,2,opt,name=Table,proto3" json:"Table,omitempty"`
	Column string `protobuf:"bytes,3,opt,name=Column,proto3" json:"Column,omitempty"`
}

func (x *FQN) Reset() {
	*x = FQN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FQN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FQN) ProtoMessage() {}

func (x *FQN) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FQN.ProtoReflect.Descriptor instead.
func (*FQN) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{21}
}

func (x *FQN) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *FQN) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *FQN) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

// 附加信息
type Extra struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grouping []*FQN `protobuf:"bytes,1,rep,name=Grouping,proto3" json:"Grouping,omitempty"` // 分组信息
	Selects  []*FQN `protobuf:"bytes,2,rep,name=Selects,proto3" json:"Selects,omitempty"`   // 最外层查询列信息
}

func (x *Extra) Reset() {
	*x = Extra{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extra) ProtoMessage() {}

func (x *Extra) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extra.ProtoReflect.Descriptor instead.
func (*Extra) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{22}
}

func (x *Extra) GetGrouping() []*FQN {
	if x != nil {
		return x.Grouping
	}
	return nil
}

func (x *Extra) GetSelects() []*FQN {
	if x != nil {
		return x.Selects
	}
	return nil
}

// 错误信息
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"` // 错误码
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`    // 错误信息
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entrypoint_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_entrypoint_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_entrypoint_proto_rawDescGZIP(), []int{23}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_entrypoint_proto protoreflect.FileDescriptor

var file_entrypoint_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x62, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x0d, 0x45, 0x6e,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x44,
	0x42, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x62,
	0x70, 0x62, 0x2e, 0x44, 0x42, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x44, 0x42, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x70, 0x72, 0x69, 0x73, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x07, 0x43, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x48,
	0x00, 0x52, 0x07, 0x43, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x88, 0x01, 0x01, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x53, 0x71, 0x6c, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x62,
	0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x06, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x12, 0x26, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x48, 0x01, 0x52,
	0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x43, 0x72,
	0x6f, 0x6e, 0x74, 0x61, 0x62, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x45, 0x78, 0x74, 0x72, 0x61, 0x22,
	0x2b, 0x0a, 0x06, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x2f, 0x0a, 0x07,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0xe4, 0x01,
	0x0a, 0x0b, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x27, 0x0a,
	0x08, 0x4f, 0x75, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x4f, 0x75,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x52, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12,
	0x41, 0x0a, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x48, 0x00, 0x52, 0x0b, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x26, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x01,
	0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x4e,
	0x65, 0x78, 0x74, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x70, 0x72, 0x69, 0x73,
	0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x05,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a,
	0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x48, 0x01, 0x52, 0x0a, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x88, 0x01,
	0x01, 0x12, 0x2c, 0x0a, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x73, 0x48, 0x02, 0x52, 0x07, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x26, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x03, 0x52, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x4b, 0x65, 0x79, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x42, 0x0a,
	0x0a, 0x08, 0x5f, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x06, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x93, 0x02,
	0x0a, 0x08, 0x44, 0x42, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x42,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x42, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x44, 0x42, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x44, 0x42, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x47, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x44, 0x42, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x40, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x3d, 0x0a, 0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x63, 0x65,
	0x12, 0x30, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72,
	0x79, 0x12, 0x36, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45,
	0x76, 0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0c, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x5d, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x72, 0x79, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x2d, 0x0a, 0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26,
	0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x22, 0xed, 0x02, 0x0a, 0x0e, 0x43, 0x79, 0x63, 0x6c, 0x65,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d,
	0x62, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x09, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x08,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x44, 0x61, 0x79, 0x48, 0x00, 0x52, 0x08, 0x45, 0x76, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x12,
	0x39, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x72, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x72, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x48, 0x00, 0x52,
	0x09, 0x45, 0x76, 0x65, 0x72, 0x79, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x3b, 0x0a, 0x0a, 0x45, 0x76,
	0x65, 0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x57, 0x65, 0x65, 0x6b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x48, 0x00, 0x52, 0x0a, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x3a, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x51, 0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79, 0x59,
	0x65, 0x61, 0x72, 0x48, 0x00, 0x52, 0x0c, 0x45, 0x76, 0x65, 0x72, 0x79, 0x51, 0x75, 0x61, 0x72,
	0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x72, 0x79, 0x59, 0x65, 0x61, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79,
	0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79, 0x59, 0x65, 0x61, 0x72, 0x48, 0x00, 0x52, 0x09,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x59, 0x65, 0x61, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x0d, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x72, 0x79, 0x44, 0x61, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e,
	0x43, 0x79, 0x63, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x07, 0x52, 0x75, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x62, 0x0a, 0x13, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x57, 0x65, 0x65, 0x6b, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x12, 0x29, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x62, 0x70,
	0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x07, 0x52, 0x75, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x44, 0x61,
	0x79, 0x52, 0x03, 0x44, 0x61, 0x79, 0x22, 0xb4, 0x01, 0x0a, 0x0e, 0x43, 0x79, 0x63, 0x6c, 0x65,
	0x45, 0x76, 0x65, 0x72, 0x79, 0x59, 0x65, 0x61, 0x72, 0x12, 0x29, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x62, 0x70,
	0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x07, 0x52, 0x75, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76,
	0x65, 0x72, 0x79, 0x59, 0x65, 0x61, 0x72, 0x2e, 0x44, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x03, 0x44, 0x61, 0x79, 0x1a, 0x46, 0x0a, 0x08, 0x44, 0x61, 0x79, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x44,
	0x61, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x37, 0x0a,
	0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x6f,
	0x75, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x16,
	0x0a, 0x06, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06,
	0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x22, 0x1c, 0x0a, 0x08, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x44,
	0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x03, 0x44, 0x61, 0x79, 0x22, 0x6b, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x5a, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x87, 0x02, 0x0a, 0x07, 0x43, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x12, 0x16, 0x0a,
	0x06, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x62,
	0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x2f, 0x0a,
	0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x63,
	0x65, 0x48, 0x00, 0x52, 0x09, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x63, 0x65, 0x12, 0x32,
	0x0a, 0x0a, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x72, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x12, 0x3e, 0x0a, 0x0e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x62, 0x70,
	0x62, 0x2e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x48, 0x00, 0x52, 0x0e, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x22, 0x4b, 0x0a, 0x03, 0x46,
	0x51, 0x4e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x53, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x12, 0x25, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x46, 0x51, 0x4e, 0x52, 0x08,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x0a, 0x07, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x62, 0x70, 0x62,
	0x2e, 0x46, 0x51, 0x4e, 0x52, 0x07, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x73, 0x22, 0x2d, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x2a, 0x64, 0x0a, 0x09,
	0x52, 0x75, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x52, 0x75, 0x6e,
	0x6e, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x08, 0x12,
	0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x10, 0x12, 0x08, 0x0a, 0x04,
	0x46, 0x61, 0x69, 0x6c, 0x10, 0x20, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x10, 0x40, 0x2a, 0x55, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x45, 0x76, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45,
	0x76, 0x4d, 0x69, 0x6e, 0x75, 0x74, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x45, 0x76, 0x48,
	0x6f, 0x75, 0x72, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x76, 0x44, 0x61, 0x79, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x45, 0x76, 0x57, 0x65, 0x65, 0x6b, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x76, 0x4d, 0x6f, 0x6e, 0x74, 0x68, 0x10, 0x05, 0x2a, 0x6c, 0x0a, 0x0d, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x76,
	0x65, 0x72, 0x79, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x76, 0x65,
	0x72, 0x79, 0x44, 0x61, 0x79, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x72, 0x79,
	0x57, 0x65, 0x65, 0x6b, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x72, 0x79, 0x4d,
	0x6f, 0x6e, 0x74, 0x68, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x72, 0x79, 0x51,
	0x75, 0x61, 0x72, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x72,
	0x79, 0x59, 0x65, 0x61, 0x72, 0x10, 0x05, 0x32, 0xb1, 0x01, 0x0a, 0x05, 0x4d, 0x42, 0x65, 0x74,
	0x6c, 0x12, 0x32, 0x0a, 0x06, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x6d, 0x62,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x07, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x0d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x23,
	0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x0d, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x6d, 0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x0d, 0x2e,
	0x6d, 0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x6d,
	0x62, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x4f, 0x0a, 0x19, 0x63,
	0x6f, 0x6d, 0x2e, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x04, 0x6d, 0x62, 0x70, 0x62, 0x50, 0x00,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6f, 0x72,
	0x68, 0x73, 0x64, 0x2f, 0x6d, 0x62, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x6d, 0x62, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x62, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entrypoint_proto_rawDescOnce sync.Once
	file_entrypoint_proto_rawDescData = file_entrypoint_proto_rawDesc
)

func file_entrypoint_proto_rawDescGZIP() []byte {
	file_entrypoint_proto_rawDescOnce.Do(func() {
		file_entrypoint_proto_rawDescData = protoimpl.X.CompressGZIP(file_entrypoint_proto_rawDescData)
	})
	return file_entrypoint_proto_rawDescData
}

var file_entrypoint_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_entrypoint_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_entrypoint_proto_goTypes = []interface{}{
	(RunStatus)(0),                // 0: mbpb.RunStatus
	(EveryType)(0),                // 1: mbpb.EveryType
	(EveryTimeType)(0),            // 2: mbpb.EveryTimeType
	(*EnableRequest)(nil),         // 3: mbpb.EnableRequest
	(*Tables)(nil),                // 4: mbpb.Tables
	(*Columns)(nil),               // 5: mbpb.Columns
	(*EnableReply)(nil),           // 6: mbpb.EnableReply
	(*Request)(nil),               // 7: mbpb.Request
	(*Reply)(nil),                 // 8: mbpb.Reply
	(*Table)(nil),                 // 9: mbpb.Table
	(*Column)(nil),                // 10: mbpb.Column
	(*DBDetail)(nil),              // 11: mbpb.DBDetail
	(*CycleOnce)(nil),             // 12: mbpb.CycleOnce
	(*CycleEvery)(nil),            // 13: mbpb.CycleEvery
	(*EveryExpress)(nil),          // 14: mbpb.EveryExpress
	(*Expression)(nil),            // 15: mbpb.Expression
	(*CycleEveryTime)(nil),        // 16: mbpb.CycleEveryTime
	(*CycleEveryDay)(nil),         // 17: mbpb.CycleEveryDay
	(*CycleEveryWeekMonth)(nil),   // 18: mbpb.CycleEveryWeekMonth
	(*CycleEveryYear)(nil),        // 19: mbpb.CycleEveryYear
	(*CycleHour)(nil),             // 20: mbpb.CycleHour
	(*CycleDay)(nil),              // 21: mbpb.CycleDay
	(*CommonConfig)(nil),          // 22: mbpb.CommonConfig
	(*Crontab)(nil),               // 23: mbpb.Crontab
	(*FQN)(nil),                   // 24: mbpb.FQN
	(*Extra)(nil),                 // 25: mbpb.Extra
	(*Error)(nil),                 // 26: mbpb.Error
	nil,                           // 27: mbpb.DBDetail.ConnectParamsEntry
	nil,                           // 28: mbpb.CycleEveryYear.DayEntry
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_entrypoint_proto_depIdxs = []int32{
	11, // 0: mbpb.EnableRequest.DBInfo:type_name -> mbpb.DBDetail
	23, // 1: mbpb.EnableRequest.Crontab:type_name -> mbpb.Crontab
	4,  // 2: mbpb.EnableRequest.Tables:type_name -> mbpb.Tables
	25, // 3: mbpb.EnableRequest.Extra:type_name -> mbpb.Extra
	9,  // 4: mbpb.Tables.Table:type_name -> mbpb.Table
	10, // 5: mbpb.Columns.Column:type_name -> mbpb.Column
	9,  // 6: mbpb.EnableReply.OutTable:type_name -> mbpb.Table
	5,  // 7: mbpb.EnableReply.Columns:type_name -> mbpb.Columns
	29, // 8: mbpb.EnableReply.NextRunTime:type_name -> google.protobuf.Timestamp
	26, // 9: mbpb.EnableReply.Error:type_name -> mbpb.Error
	5,  // 10: mbpb.Reply.Columns:type_name -> mbpb.Columns
	26, // 11: mbpb.Reply.Error:type_name -> mbpb.Error
	27, // 12: mbpb.DBDetail.ConnectParams:type_name -> mbpb.DBDetail.ConnectParamsEntry
	15, // 13: mbpb.CycleOnce.Expression:type_name -> mbpb.Expression
	14, // 14: mbpb.CycleEvery.EveryExpress:type_name -> mbpb.EveryExpress
	15, // 15: mbpb.CycleEvery.Expression:type_name -> mbpb.Expression
	1,  // 16: mbpb.EveryExpress.CycleType:type_name -> mbpb.EveryType
	2,  // 17: mbpb.CycleEveryTime.EveryType:type_name -> mbpb.EveryTimeType
	17, // 18: mbpb.CycleEveryTime.EveryDay:type_name -> mbpb.CycleEveryDay
	18, // 19: mbpb.CycleEveryTime.EveryWeek:type_name -> mbpb.CycleEveryWeekMonth
	18, // 20: mbpb.CycleEveryTime.EveryMonth:type_name -> mbpb.CycleEveryWeekMonth
	19, // 21: mbpb.CycleEveryTime.EveryQuarter:type_name -> mbpb.CycleEveryYear
	19, // 22: mbpb.CycleEveryTime.EveryYear:type_name -> mbpb.CycleEveryYear
	20, // 23: mbpb.CycleEveryDay.RunTime:type_name -> mbpb.CycleHour
	20, // 24: mbpb.CycleEveryWeekMonth.RunTime:type_name -> mbpb.CycleHour
	21, // 25: mbpb.CycleEveryWeekMonth.Day:type_name -> mbpb.CycleDay
	20, // 26: mbpb.CycleEveryYear.RunTime:type_name -> mbpb.CycleHour
	28, // 27: mbpb.CycleEveryYear.Day:type_name -> mbpb.CycleEveryYear.DayEntry
	22, // 28: mbpb.Crontab.CommonConfig:type_name -> mbpb.CommonConfig
	12, // 29: mbpb.Crontab.CycleOnce:type_name -> mbpb.CycleOnce
	13, // 30: mbpb.Crontab.CycleEvery:type_name -> mbpb.CycleEvery
	16, // 31: mbpb.Crontab.CycleEveryTime:type_name -> mbpb.CycleEveryTime
	24, // 32: mbpb.Extra.Grouping:type_name -> mbpb.FQN
	24, // 33: mbpb.Extra.Selects:type_name -> mbpb.FQN
	21, // 34: mbpb.CycleEveryYear.DayEntry.value:type_name -> mbpb.CycleDay
	3,  // 35: mbpb.MBetl.Enable:input_type -> mbpb.EnableRequest
	7,  // 36: mbpb.MBetl.Disable:input_type -> mbpb.Request
	7,  // 37: mbpb.MBetl.Run:input_type -> mbpb.Request
	7,  // 38: mbpb.MBetl.Cancel:input_type -> mbpb.Request
	6,  // 39: mbpb.MBetl.Enable:output_type -> mbpb.EnableReply
	8,  // 40: mbpb.MBetl.Disable:output_type -> mbpb.Reply
	8,  // 41: mbpb.MBetl.Run:output_type -> mbpb.Reply
	8,  // 42: mbpb.MBetl.Cancel:output_type -> mbpb.Reply
	39, // [39:43] is the sub-list for method output_type
	35, // [35:39] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_entrypoint_proto_init() }
func file_entrypoint_proto_init() {
	if File_entrypoint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entrypoint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tables); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Columns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleOnce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleEvery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EveryExpress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleEveryTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleEveryDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleEveryWeekMonth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleEveryYear); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CycleDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crontab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FQN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Extra); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entrypoint_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_entrypoint_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_entrypoint_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_entrypoint_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_entrypoint_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_entrypoint_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*CycleEveryTime_EveryDay)(nil),
		(*CycleEveryTime_EveryWeek)(nil),
		(*CycleEveryTime_EveryMonth)(nil),
		(*CycleEveryTime_EveryQuarter)(nil),
		(*CycleEveryTime_EveryYear)(nil),
	}
	file_entrypoint_proto_msgTypes[19].OneofWrappers = []interface{}{}
	file_entrypoint_proto_msgTypes[20].OneofWrappers = []interface{}{
		(*Crontab_CycleOnce)(nil),
		(*Crontab_CycleEvery)(nil),
		(*Crontab_CycleEveryTime)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entrypoint_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entrypoint_proto_goTypes,
		DependencyIndexes: file_entrypoint_proto_depIdxs,
		EnumInfos:         file_entrypoint_proto_enumTypes,
		MessageInfos:      file_entrypoint_proto_msgTypes,
	}.Build()
	File_entrypoint_proto = out.File
	file_entrypoint_proto_rawDesc = nil
	file_entrypoint_proto_goTypes = nil
	file_entrypoint_proto_depIdxs = nil
}
